# Change these first
owner: v4lerio # Your GitHub organization or username, where this repository lives
repo: infosecnews-help-gov-it # The name of this repository

sites:
  - name: Parlamento
    url: https://www.parlamento.it/
    maxResponseTime: 5000
  - name: Agenzia delle Entrate
    url: https://www.agenziaentrate.gov.it/
    maxResponseTime: 5000
  - name: Governo
    url: https://www.governo.it/
    maxResponseTime: 5000
  - name: Salute
    url: http://www.salute.gov.it/
    maxResponseTime: 5000
  - name: Esteri
    url: https://www.esteri.it/
    maxResponseTime: 5000
  - name: Giustizia
    url: https://www.giustizia.it/
    maxResponseTime: 5000
  - name: Interno
    url: https://www.interno.gov.it/
    maxResponseTime: 5000
  - name: Difesa
    url: https://www.difesa.it/
    maxResponseTime: 5000
  - name: Economia e Finance (MEF)
    url: https://www.mef.gov.it/
    maxResponseTime: 5000
  - name: Sviluppo Economico
    url: https://www.mise.gov.it/
    maxResponseTime: 5000
  - name: Universit&agrave; e Ricerca (MUR)
    url: https://www.mur.gov.it/
    maxResponseTime: 5000
  - name: Lavoro
    url: https://www.lavoro.gov.it/
    maxResponseTime: 5000
  - name: Infrastrutture e Trasporti
    url: https://www.mit.gov.it/
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /infosecnews-help-gov-it
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HelpGovIT
  introTitle: "***HelpGovIT*** - Micro progetto di supporto informativo."
  introMessage: "Di seguito lo status dei portali web dei ministeri Italiani al servizio del cittadino..."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
